# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L3lsqXMolhPw1JoJxBnC1fQJP5mLxNwj
"""

SU=0
for i in range (0,30):
  vendio=input("Se vendio otro numero S/n:")
  if vendio=="S":
   SU=SU+100
  print("Lo recaudado es:",SU)